### ISSUE TITLE
Project descriptions.

### ISSUE THREAD

**Issue by imsabbir-dev** [excel-azmin/excel_frappe#1]
Project description is not clear need to add a well organized project description so any contributor can understand about the project and contribute it.

![image](https://github.com/excel-azmin/excel_frappe/assets/29356354/0f0cc11e-df33-40d8-a48f-ae3bd02b7f38)

**Comment by excel-azmin** [comment]
Project description has been updated. Please check and feel free to contiribute or any suggestion
